# Generated by Django 3.1.1 on 2020-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalore', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(null=True),
        ),
    ]
