# Generated by Django 3.1.1 on 2020-09-22 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalore', '0004_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 12, 26, 31, 332247)),
        ),
    ]
