# Generated by Django 3.1.1 on 2020-09-22 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalore', '0005_auto_20200922_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.PNG', upload_to='img_product'),
        ),
        migrations.AlterField(
            model_name='support',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 15, 5, 13, 50645)),
        ),
    ]
