# Generated by Django 3.1.1 on 2020-09-22 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalore', '0006_auto_20200922_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='support',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 19, 38, 6, 396829)),
        ),
    ]
